title: 所羅門王的寶藏
description: 晚安．月亮─床邊故事：所羅門王的寶藏
time: Tue, 26 Mar 2024 01:37:57 +0000
items:
  - title: 00. 所羅門王的寶藏
    size: 977885
    duration: 95
  - title: 01. 獵象高手克達勉
    size: 4232959
    duration: 435
  - title: 02. 性命垂危的白人探險家
    size: 5227698
    duration: 536
  - title: 03. 神秘的地圖
    size: 5426593
    duration: 561
  - title: 04. 喬治‧卡迪士
    size: 5367269
    duration: 542
  - title: 05. 意外的訪客
    size: 4565581
    duration: 479
  - title: 06. 青年文寶柏
    size: 4875188
    duration: 511
  - title: 07. 玻璃片先生
    size: 5171552
    duration: 542
  - title: 08. 獵象行動
    size: 4808947
    duration: 492
  - title: 09. 神秘的文寶柏
    size: 4532293
    duration: 464
  - title: 10. 月夜中向前進
    size: 5160533
    duration: 532
  - title: 11. 炎熱的沙漠
    size: 5103823
    duration: 527
  - title: 12. 救命的水池
    size: 4488147
    duration: 457
  - title: 13. 飢餓與寒冷
    size: 5266327
    duration: 536
  - title: 14. 山洞中的一夜
    size: 4523899
    duration: 459
  - title: 15. 神秘的死屍
    size: 5282029
    duration: 535
  - title: 16. 獵獲大鹿
    size: 4471203
    duration: 455
  - title: 17. 愛乾淨的古特上校
    size: 4712997
    duration: 478
  - title: 18. 來自外星球的神仙
    size: 5162970
    duration: 516
  - title: 19. 伊哈德與思克拉
    size: 4770775
    duration: 477
  - title: 20. 古卦那國的歷史
    size: 5520113
    duration: 556
  - title: 21. 愉快的旅行
    size: 5178381
    duration: 522
  - title: 22. 謁見國王
    size: 4848792
    duration: 487
  - title: 23. 殘忍的茲瓦拉王
    size: 5664760
    duration: 560
  - title: 24. 妖婆葛考爾的預言
    size: 4989648
    duration: 498
  - title: 25. 伊哈德的隱憂
    size: 5004023
    duration: 503
  - title: 26. 文寶柏的身世
    size: 4576227
    duration: 461
  - title: 27. 恐怖的舞會
    size: 5304259
    duration: 521
  - title: 28. 殘忍的審判
    size: 5151097
    duration: 517
  - title: 29. 文寶柏的危機
    size: 4974891
    duration: 518
  - title: 30. 隊長的質疑
    size: 4231016
    duration: 441
  - title: 31. 古特上校的妙計
    size: 4754167
    duration: 493
  - title: 32. 最美的少女
    size: 5135860
    duration: 537
  - title: 33. 神蹟
    size: 4863437
    duration: 506
  - title: 34. 伊古諾王萬歲
    size: 4192748
    duration: 426
  - title: 35. 戰鬥開始
    size: 5237990
    duration: 530
  - title: 36. 一觸即發
    size: 4416802
    duration: 441
  - title: 37. 慘烈的戰爭
    size: 5159001
    duration: 530
  - title: 38. 一分為三
    size: 4623261
    duration: 464
  - title: 39. 最後的決鬥
    size: 5095237
    duration: 518
  - title: 40. 全軍覆沒
    size: 3927342
    duration: 404
  - title: 41. 茲瓦拉王的最後掙扎
    size: 4737969
    duration: 489
  - title: 42. 高唱凱歌
    size: 4298927
    duration: 442
  - title: 43. 寶藏探險計畫
    size: 5054809
    duration: 524
  - title: 44. 危險的嚮導
    size: 4439187
    duration: 456
  - title: 45. 無言神的石像
    size: 4889559
    duration: 503
  - title: 46. 國王的陵墓
    size: 4309238
    duration: 441
  - title: 47. 閃亮的鑽石
    size: 4670211
    duration: 482
  - title: 48. 密室裡的寶藏
    size: 4773233
    duration: 488
  - title: 49. 葛考爾的末日
    size: 4995333
    duration: 521
  - title: 50. 石環下的秘密
    size: 4183187
    duration: 421
  - title: 51. 一線曙光
    size: 4401345
    duration: 452
  - title: 52. 再見伊古諾王
    size: 4576572
    duration: 469
  - title: 53. 永遠的光榮
    size: 4041008
    duration: 418
  - title: 54. 奇妙的重逢
    size: 4487018
    duration: 452
  - title: 55. 好友的來信
    size: 4951180
    duration: 502
